# Generated by Django 5.2.3 on 2026-06-11 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brendi')),
                ('camera_type', models.CharField(max_length=100, verbose_name='Turi (IP, Analog va h.k.)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Soni')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='kamera.station')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brendi/Modeli')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Soni')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='kamera.station')),
            ],
        ),
        migrations.CreateModel(
            name='MetalDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brendi')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Soni')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metal_detectors', to='kamera.station')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Markasi/Brendi')),
                ('size', models.CharField(max_length=50, verbose_name="O'lchami (dyuym)")),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Soni')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='kamera.station')),
            ],
        ),
        migrations.CreateModel(
            name='NVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brendi')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modeli')),
                ('ports_count', models.PositiveIntegerField(verbose_name='Portlar soni')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Soni')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nvrs', to='kamera.station')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_type', models.CharField(max_length=100, verbose_name='Turi (PoE, Oddiy va h.k.)')),
                ('ports_count', models.PositiveIntegerField(verbose_name='Portlar soni')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Xususiyati/Tavsifi')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Soni')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='kamera.station')),
            ],
        ),
    ]
