# Generated by Django 5.2.3 on 2026-06-12 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0002_camera_computer_metaldetector_monitor_nvr_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50, verbose_name='Qurilma turi')),
                ('device_id', models.IntegerField(blank=True, null=True, verbose_name='Qurilma ID')),
                ('device_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qurilma brendi')),
                ('action', models.CharField(max_length=50, verbose_name='Harakat turi')),
                ('quantity_change', models.IntegerField(default=0, verbose_name="Soni o'zgarishi")),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh/Komentariya')),
                ('user_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Foydalanuvchi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_histories', to='kamera.station')),
            ],
        ),
    ]
