# Generated by Django 5.2.3 on 2026-06-15 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0003_devicehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='Masalan: 192.168.1.100 yoki rtsp://192.168.1.100:554/stream', max_length=255, verbose_name='IP manzil')),
                ('login', models.CharField(default='admin', max_length=100, verbose_name='Login')),
                ('password', models.CharField(max_length=100, verbose_name='Parol')),
                ('rtsp_port', models.IntegerField(default=554, verbose_name='RTSP Port')),
                ('http_port', models.IntegerField(default=80, verbose_name='HTTP Port')),
                ('stream_path', models.CharField(blank=True, default='/stream', help_text='Masalan: /stream1 yoki /video/ch0_0', max_length=255, null=True, verbose_name="Stream yo'li")),
                ('pos_x', models.FloatField(default=50.0, help_text='Sxema rasmida kameraning gorizontal joyi (0-100%)', verbose_name='X pozitsiya (%)')),
                ('pos_y', models.FloatField(default=50.0, help_text='Sxema rasmida kameraning vertikal joyi (0-100%)', verbose_name='Y pozitsiya (%)')),
                ('direction', models.IntegerField(default=0, help_text="0=o'ng, 90=quyi, 180=chap, 270=yuqori", verbose_name="Yo'nalish (gradus)")),
                ('label', models.CharField(blank=True, help_text='Kamera uchun qisqa nom (masalan: Kirish, Platforma-1)', max_length=100, null=True, verbose_name='Yorliq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream_info', to='kamera.camera', verbose_name='Kamera')),
            ],
        ),
    ]
