# Generated by Django 5.2.3 on 2026-06-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0004_camerastream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerastream',
            name='stream_path',
            field=models.CharField(blank=True, default='/Streaming/Channels/101', help_text='Masalan: /stream1 yoki /video/ch0_0', max_length=255, null=True, verbose_name="Stream yo'li"),
        ),
    ]
