# Generated by Django 5.2.3 on 2026-06-16 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0005_alter_camerastream_stream_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.IntegerField(help_text='Sxemadagi kameraning tartib raqami (masalan: 1, 2, 3...)', verbose_name='Joy raqami')),
                ('label', models.CharField(blank=True, help_text='Kamera uchun qisqa nom (masalan: Kirish, Platforma-1)', max_length=100, null=True, verbose_name='Yorliq/Nomi')),
                ('ip_address', models.CharField(help_text='Masalan: 192.168.1.100', max_length=255, verbose_name='IP manzil')),
                ('login', models.CharField(default='admin', max_length=100, verbose_name='Login')),
                ('password', models.CharField(max_length=100, verbose_name='Parol')),
                ('rtsp_port', models.IntegerField(default=554, verbose_name='RTSP Port')),
                ('http_port', models.IntegerField(default=80, verbose_name='HTTP Port')),
                ('stream_path', models.CharField(blank=True, default='/Streaming/Channels/101', max_length=255, null=True, verbose_name="Stream yo'li")),
                ('pos_x', models.FloatField(default=50.0, verbose_name='X pozitsiya (%)')),
                ('pos_y', models.FloatField(default=50.0, verbose_name='Y pozitsiya (%)')),
                ('direction', models.IntegerField(default=0, verbose_name="Yo'nalish (gradus)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_cameras', to='kamera.station', verbose_name='Bekat')),
            ],
            options={
                'verbose_name': 'Sxema Kamerasi',
                'verbose_name_plural': 'Sxema Kameralari',
                'ordering': ['position_number'],
            },
        ),
    ]
