# Generated by Django 5.2.3 on 2026-06-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0007_schemacamera_is_local_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacamera',
            name='is_local_only',
            field=models.BooleanField(default=False, help_text='Lokal IP — stream stansiya PC (Local Agent) orqali', verbose_name='Faqat lokal tarmoq'),
        ),
    ]
